Endleaf rejiggle, .fsm syntax for endids, refactor endid get/set api, various related bugfixes
katef/libfsm pull request #479
Opened 2024-06-16 22:35 UTC by katef

I did quite a few things here, all focused around the endleaf callbacks,
and by extension the endid mechanism. I fixed a few small bugs, and got distracted trying to tidy up a bit.

Anyway here's what we get:

* .fsm syntax support for endids
* Add missing printing for endids for various formats (notably dot and .fsm)
* Various work on ways to simplify the endids API, especially:
  * Removed &nwritten for fsm_endid_get(), we don't need partial gets
  * Removed the tri-state enums for fsm_endid_get/set()
  * We don't need to distinguish a state absent endids from a present but empty set of endids
* Add missing calls to endleaf() callbacks for various formats
* Reintroduced fsm_exec handling in re(1), and reworked related argv[] handling. This is neccessary bugfixes only, in particular I want to address #478 and #477 separately
* Bugfixes around the api format codegen, that was quite out of date.

The .fsm syntax for endids looks like this:
```
; ./build/bin/re -r pcre -bpl fsm 'ab?c' 'abc*'
0  ->  1 "a"; # e.g. "a"
1  ->  2 "b"; # e.g. "ab"
1  ->  3 "c"; # e.g. "ac"
2  ->  4 "c"; # e.g. "abc"
4  ->  5 "c"; # e.g. "abcc"
5  ->  5 "c"; # e.g. "abcc"

start: 0;
end:   2 = [0], 3 = [0], 4 = [0, 1], 5 = [0];
```
and renders out like:
![image](https://github.com/katef/libfsm/assets/1371085/7147b67b-915e-4efd-b63a-220bbcb91816)

2024-06-17 17:46 UTC, silentbicycle requested changes
Do you have a better suggestion for how to pass a handle to the caller besides `void *opaque` that isn't significantly more complicated in a multi-threaded context?

2024-06-17 23:18 UTC, katef commented on src/libfsm/print/c.c
> -			fprintf(f, "(const char *s, void *opaque)\n");
You could still use a `void *opaque` if you like! But my point is with `.fragment = true` output, that's the responsibility of the API-user, it's not something that belongs to libfsm's generated code. That's why I'm removing it here.

2024-06-17 23:19 UTC, katef commented on include/fsm/fsm.h
> +    size_t id_buf_count, fsm_end_id_t *id_buf);
Right, and I dealt with those situations.

2024-06-18 18:21 UTC, silentbicycle commented on include/fsm/fsm.h
> +    size_t id_buf_count, fsm_end_id_t *id_buf);
Yes, just providing context.

2024-06-18 18:23 UTC, silentbicycle commented on src/libfsm/print/c.c
> -			fprintf(f, "(const char *s, void *opaque)\n");
Okay, that works for me.

2024-06-18 18:23 UTC, silentbicycle approved these changes

2024-06-18 18:41 UTC, merged